### ISSUE TITLE
httpapi error with netcommon 5.0.0

### ISSUE THREAD

**Issue by pilem** [ansible-collections/community.zabbix#923]
I get the following error with netcommon 5.0.0
```
'Connection' object has no attribute 'zbx_api_version'
```
Works fine with netcommon 4.1.0

**Comment by pilem** [comment]
Very good, thanks.
